version: 2.1

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore:  /.*/
              
jobs: 
  build:
    macos:  
      xcode: 11.3.0
    steps:
      - checkout
      - set-directory
      - add-pixlee-credentials
      - ui-tests
  deploy:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - set-directory
      - deploy-cooapods
      
commands:
  set-directory:
    steps:
      - run:
          name: set directory
          command: pod install --project-directory=Example
  add-pixlee-credentials:
    steps:
      - run:
          name: add pixlee credentials
          command: |
            echo $PIXLEE_CREDENTIALS | base64 --decode > Example/Example/PixleeCredentials.plist
            ls -al Example/Example
  ui-tests:
    steps:
      - run:
          name: UI tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: ExampleUITests

  deploy-cooapods:
    steps:
      - run:
          name: deploy cooapods
          command:  |
            export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
            pod lib lint --allow-warnings
            pod trunk push --allow-warnings
